apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-route-template
labels:
  template: ${APPLICATION_NAME}-route-template
objects:
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: gla-api
    namespace: ec1236-dev
    labels:
      app: gla-api
      app.kubernetes.io/part-of: gla
    annotations:
      openshift.io/host.generated: 'true'
  spec:
    host: gla-api-ec1236-dev.apps.silver.devops.gov.bc.ca
    path: /api
    to:
      kind: Service
      name: gla-api
      weight: 100
    port:
      targetPort: 3000-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: gla-api
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: License Plate
    displayName: License Plate
    name: LICENSE_PLATE
    required: true
    value: ec1236
  - description: Imagestream
    displayName: Imagestream
    name: IMAGESTREAM
    required: true
    value: 'gla-api'