apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: gla-api
    namespace: ec1236-dev
    labels:
      app: gla-api
      app.kubernetes.io/part-of: gla-api
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
  spec:
    ipFamilies:
      - IPv4
    ports:
      - name: 3000-tcp
        protocol: TCP
        port: 3000
        targetPort: 3000
    internalTrafficPolicy: Cluster
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    sessionAffinity: None
    selector:
      app: gla-api
      deploymentconfig: gla-api

parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: gla-api
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: License Plate
    displayName: License Plate
    name: LICENSE_PLATE
    required: true
    value: ec1236
  - description: Imagestream
    displayName: Imagestream
    name: IMAGESTREAM
    required: true
    value: 'gla-api'